# Generated by Django 3.2.12 on 2022-02-17 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0035_auto_20211109_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveConstraint(
            model_name='featurestate',
            name='unique_for_feature_segment',
        ),
        migrations.RemoveConstraint(
            model_name='featurestate',
            name='unique_for_identity',
        ),
        migrations.RemoveConstraint(
            model_name='featurestate',
            name='unique_for_environment',
        ),
        migrations.AddField(
            model_name='featurestate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featurestate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMMITTED', 'Committed')], default='COMMITTED', max_length=50),
        ),
        migrations.AddField(
            model_name='featurestate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='featurestate',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMMITTED', 'Committed')], default='COMMITTED', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='featurestate',
            constraint=models.UniqueConstraint(condition=models.Q(('identity__isnull', True)), fields=('environment', 'feature', 'feature_segment', 'version'), name='unique_for_feature_segment'),
        ),
        migrations.AddConstraint(
            model_name='featurestate',
            constraint=models.UniqueConstraint(condition=models.Q(('feature_segment__isnull', True)), fields=('environment', 'feature', 'identity', 'version'), name='unique_for_identity'),
        ),
        migrations.AddConstraint(
            model_name='featurestate',
            constraint=models.UniqueConstraint(condition=models.Q(('feature_segment__isnull', True), ('identity__isnull', True)), fields=('environment', 'feature', 'version'), name='unique_for_environment'),
        ),
    ]
