# Generated by Django 2.2.26 on 2022-02-07 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0035_auto_20211109_0603"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="featurestate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="featurestate",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("COMMITTED", "Committed")],
                max_length=50,
                null=True,
                default="COMMITTED",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="featurestate",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("COMMITTED", "Committed")],
                max_length=50,
                default="DRAFT",
            ),
        ),
        migrations.AddField(
            model_name="featurestate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="featurestate",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="historicalfeaturestate",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalfeaturestate",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("COMMITTED", "Committed")],
                max_length=50,
                null=True,
                default="COMMITTED",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalfeaturestate",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("COMMITTED", "Committed")],
                max_length=50,
                default="DRAFT",
            ),
        ),
        migrations.AddField(
            model_name="historicalfeaturestate",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalfeaturestate",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
