# Generated by Django 2.2.26 on 2022-02-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0036_add_feature_state_versioning_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='featurestate',
            name='unique_for_environment',
        ),
        migrations.AddConstraint(
            model_name='featurestate',
            constraint=models.UniqueConstraint(condition=models.Q(('feature_segment__isnull', True), ('identity__isnull', True)), fields=('environment', 'feature', 'version'), name='unique_for_environment'),
        ),
    ]
