# Generated by Django 3.2.12 on 2022-02-17 17:14

from django.db import migrations, models
from django.contrib.postgres.operations import (
    RemoveIndexConcurrently,
    AddIndexConcurrently,
)
import django.utils.timezone


idx_names = (
    f"unique_for_{model}" for model in ("environment", "identity", "feature_segment")
)


def add_unique_constraints(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE UNIQUE INDEX "unique_for_feature_segment" 
                ON "features_featurestate" ("environment_id", "feature_id", "feature_segment_id", "version") 
                WHERE "identity_id" IS NULL;
            CREATE UNIQUE INDEX "unique_for_identity" 
                ON "features_featurestate" ("environment_id", "feature_id", "identity_id", "version") 
                WHERE "feature_segment_id" IS NULL;
            CREATE UNIQUE INDEX "unique_for_environment" 
                ON "features_featurestate" ("environment_id", "feature_id", "version") 
                WHERE ("feature_segment_id" IS NULL AND "identity_id" IS NULL);
        """
        )
    else:
        feature_state_model_class = apps.get_model("features", "featurestate")
        schema_editor.add_constraint(
            model=feature_state_model_class,
            constraint=models.UniqueConstraint(
                condition=models.Q(("identity__isnull", True)),
                fields=("environment", "feature", "feature_segment", "version"),
                name="unique_for_feature_segment",
            ),
        )
        schema_editor.add_constraint(
            model=feature_state_model_class,
            constraint=models.UniqueConstraint(
                condition=models.Q(("feature_segment__isnull", True)),
                fields=("environment", "feature", "identity", "version"),
                name="unique_for_identity",
            ),
        )
        schema_editor.add_constraint(
            model=feature_state_model_class,
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("feature_segment__isnull", True), ("identity__isnull", True)
                ),
                fields=("environment", "feature", "version"),
                name="unique_for_environment",
            ),
        )


def remove_unique_constraints(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for idx_name in idx_names:
            schema_editor.execute(f"DROP INDEX CONCURRENTLY {idx_name};")
    else:
        feature_state_model_class = apps.get_model("features", "featurestate")
        schema_editor.remove_constraint(
            model=feature_state_model_class,
            constraint=models.UniqueConstraint(
                condition=models.Q(("identity__isnull", True)),
                fields=("environment", "feature", "feature_segment", "version"),
                name="unique_for_feature_segment",
            ),
        )
        schema_editor.remove_constraint(
            model=feature_state_model_class,
            constraint=models.UniqueConstraint(
                condition=models.Q(("feature_segment__isnull", True)),
                fields=("environment", "feature", "identity", "version"),
                name="unique_for_identity",
            ),
        )
        schema_editor.remove_constraint(
            model=feature_state_model_class,
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("feature_segment__isnull", True), ("identity__isnull", True)
                ),
                fields=("environment", "feature", "version"),
                name="unique_for_environment",
            ),
        )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("features", "0037_add_feature_state_versioning_fields"),
    ]

    operations = [
        migrations.RunPython(
            add_unique_constraints,
            reverse_code=remove_unique_constraints,
            atomic=False,
        ),
    ]
